### ISSUE TITLE
Workspaces value does not match match config value

### ISSUE THREAD

**Issue by chrissound** [xmonad/xmonad-contrib#152]
### Problem Description

I've recently upgraded to xmonad 0.13 and xmonad-contrib 0.13, ever since I'm getting a different set of workspaces then defined in my config. I'm getting the default 1-9 workspaces instead of the 1-4 I've defined within the config.

### Configuration File
```
import XMonad
import XMonad.Config.Desktop
import XMonad.Hooks.ManageDocks

import XMonad.Hooks.Minimize
import XMonad.Layout.Minimize

main = xmonad desktopConfig
    { terminal           = "termite"
    , modMask     = mod4Mask
    , layoutHook         = minimize . desktopLayoutModifiers . avoidStruts $ layoutHook desktopConfig
    , workspaces = ["1", "2", "3", "4"]
    , manageHook = manageHook desktopConfig <+> manageDocks
    , handleEventHook = minimizeEventHook
    }
```
I get the following output behavior within GHCi (which seems correct):
```
workspaces $ desktopConfig { workspaces = ["1"] }
["1"]
```

**Comment by chrissound** [comment]
If I change the workspaces to `["a", "b", "c", "d"]` I get a set of workspaces of `a, b, c, d, 3, 4, 7, 8, 9`.

**Comment by geekosaur** [comment]
I think someone needs to drop a trace around `defaultConfig`'s `workspaces` to see if it gets evaluated before the user config is installed.

@chrissound, can you try this with a config based on `defaultConfig` instead of `desktopConfig`? An additional test might be to remove `desktopLayoutModifiers` from the `layoutHook`. (This is probing for a specific reference that might be happening.)

And you should remove the `avoidStruts` in any case; `desktopLayoutModifiers` handles it (and in the future will likely handle more things as well).

**Comment by chrissound** [comment]
Interestingly if I set the workspaces to `["1", "2", "3]`, quit xmonad (modMask + Q) and execute `startx` - then get a set of workspaces with values of `1, 2, 3, 8, 9, c, d...` - so it must be picking up these old values from somewhere? 

Here is a further minimal config:
```
import XMonad
import qualified Data.Map as M
import XMonad.Actions.CycleWS

main = xmonad $ def {
          modMask     = mod4Mask
        , workspaces = ["1", "2", "3"]
        , terminal           = "lxterminal"
        , keys = myKeys <+> keys def
        }

myKeys conf@XConfig {XMonad.modMask = modm} = M.fromList [
               ((modm, xK_e), prevWS)
             , ((modm, xK_u), nextWS)
             ]
```

**Comment by chrissound** [comment]
I deleted the `~/.xmonad/xmonad.state` file and then restarted and got the correct workspace values.
