### ISSUE TITLE
Remove xinerama/gnome-panel ewmh stuff

### ISSUE THREAD

**Issue by IvanMalison** [xmonad/xmonad-contrib#216]
e153c6d40651493162230028787f1e7353a4aae6 Introduced a hack that makes it so that
"we display all visible windows on the current desktop." It seems like this should be something that is only optionally enabled (gnome-panel is not relevant to most people's configuration). @nomeata can you comment on why this was made the default behavior?

**Comment by nomeata** [comment]
I would be surprised if the be haviour that this works around is gnome-specific: If you have two screens, then xmonad displays two desktops simultaneous. EWMH does not allow to express that. But it is really strange (or even caused weird further effects, I do not remember) if there are windows currently visible that are not shown as “currently visible” on the pager.

Are there problems with the hack in other configurations?

**Comment by IvanMalison** [comment]
@nomeata https://github.com/travitch/taffybar uses a separate X11 property to communicate about which workspaces are visible.

It is important to have accurate information about which window is in which workspaces because taffybar displays window icons in it's workspace switcher widget. See this issue: https://github.com/travitch/taffybar/issues/239 

> But it is really strange (or even caused weird further effects, I do not remember) if there are windows currently visible that are not shown as “currently visible” on the pager.

What 'pager' are you referring to? This seems very specific to gnome-panel or whatever switcher you happen to be using. I have been running xmonad with this change removed for almost a year now with no issues.

**Comment by kronn** [comment]
I second that. I ran into this behaviour when showing occupied workspaces in polybars (https://github.com/jaagr/polybar/pull/882). I now know the problem, so I can mentally workaround. Still, it is strange that workspaces I see are not occupied, according to EWMH... Since I know which windows belong on which workspace, I can work with it, but it's a conscious effort, as miniscule as it may be.

I understand that gnome-panel in itself has a higher userbase than other status-bars but it would be nice to have at least a configuration-option to choose which one the user actually wants/needs.

**Comment by nomeata** [comment]
I actually stopped using multiple monitors and gnome-panel, so I am happy to yield to this decade’s user’s needs :-)

**Comment by LeifW** [comment]
I got hit by this, too, and would appreciate a fix.
