### ISSUE TITLE
Enhancement: Cycle across windows on all visible workspaces

### ISSUE THREAD

**Issue by alhirzel** [xmonad/xmonad-contrib#293]
### Enhancement

Provide a query to allow cycling across all visible windows (i.e. for multi-screen setups).

### Details

This was discussed in [this mailing list thread](https://mail.haskell.org/pipermail/xmonad/2017-February/015218.html) but did not seem to be resolved. The request is for a window switching method that allows for tabbing across all visible workspaces. I would like to submit the following `Query Bool` for use with `nextMatch` (from `XMonad.Actions.GroupNavigation`):

```haskell
isOnVisibleWS :: Query Bool
isOnVisibleWS = do
  w <- ask
  ws <- liftX $ gets windowset
  let allVisible = concat $ (maybe [] W.integrate) . W.stack . W.workspace <$> W.current ws:W.visible ws
      visibleWs = w `elem` allVisible
      unfocused = maybe True (w /=) $ W.peek ws
  return $ visibleWs && unfocused
```

Example usage:

```haskell
import XMonad.Actions.GroupNavigation (historyHook, nextMatch, Direction(..))
```

within the keys section

```
    -- use Alt+Tab and Alt+Shift+Tab to change focus to different windows across workspaces
    ((alt,           xK_Tab   ), nextMatch Forward isOnVisibleWS),
    ((alt .|. shift, xK_Tab   ), nextMatch Backward isOnVisibleWS),
```

**Comment by mgsloan** [comment]
LGTM.

Side note is that it would be more efficient to compute `allVisibleWs` ahead of time.  Probably not entirely necessary since the number of workspaces is typically quite low, GHC may even be clever enough to inline and share the computation.

**Comment by byorgey** [comment]
Looks good to me too.  Any ideas which module this should go in?  I guess we could just stick it in `XMonad.Actions.GroupNavigation` but it seems more generally applicable than that.  `XMonad.Hooks.ManageHelpers` is another place with several `Query Bool` things defined, though it doesn't seem super relevant.  In the end maybe `XMonad.Actions.GroupNavigation` is the best place for it, since that's the context in which folks are likely to want it.

@alhirzel , do you want to take a shot at opening a pull request that adds this?  We'd be happy to provide some guidance on how to do that if you need it.

**Comment by alhirzel** [comment]
I took a swing at it in #294.
