### ISSUE TITLE
[EZConfig] bug in checkKeymap

### ISSUE THREAD

**Issue by schoettl** [xmonad/xmonad-contrib#3]
I think I have found a bug in `EZConfig`:

The `checkKeymap` function does not work correctly.

My version of contrib should be the latest; `darcs pull` comes with no updates.

## Reproduce:

Use this Xmonad configuration:

````Haskell
import XMonad
import XMonad.Config
import XMonad.Util.EZConfig

main = do
    xmonad $ defaultConfig
        { modMask = mod4Mask -- Win key
        , startupHook = return () >> checkKeymap defaultConfig keysToAdd
        }
        `removeKeysP` keysToRemove
        `additionalKeysP` keysToAdd

keysToRemove :: [String]
keysToRemove =
    [ "M-a"
    , "M1-a"
    ]

keysToAdd :: [(String, X ())]
keysToAdd =
    [ ("M-a", spawn "xmessage M-a")
    , ("M1-a", spawn "xmessage M1-a=Alt-a")
    ]
`````

## Result:

````
Warning:

duplicate keybindings detected: "M-a"
````

## Expected:

(No Warnings)

Anyway both shortcuts are working as defined.

I hope it is easy to fix!

**Comment by byorgey** [comment]
Thanks for the report!  But actually, this is not a bug.  The problem is that you are passing `defaultConfig` as an argument to `checkKeymap`.  In the `defaultConfig`, the `modMask` is defined to be `mod1Mask`.  So `checkKeymap` is checking for duplicates under the assumption that mod = mod1.

The best solution is to give your entire configuration a name, and pass that to `checkKeymap` instead of `defaultConfig`.  Something like this:
```
main = xmonad myConfig

myConfig = defaultConfig
        { modMask = mod4Mask -- Win key
        , startupHook = return () >> checkKeymap myConfig keysToAdd
        }
        `removeKeysP` keysToRemove
        `additionalKeysP` keysToAdd
```
Alternatively, you could just pass `(defaultConfig { modMask = mod4Mask })` as the argument to `checkKeymap`, which is a bit simpler (you don't have to worry about whether your recursively defined config is well-defined!) but assumes that `checkKeymap` only looks at the `modMask` (I think this is true but not 100% sure off the top of my head) and also means if you ever want to change your `modMask` you now have to change your config in two places.

**Comment by geekosaur** [comment]
On Fri, Sep 18, 2015 at 12:44 AM, Jakob Schöttl <notifications@github.com>
wrote:

>         `removeKeysP` keysToRemove
>         `additionalKeysP` keysToAdd
> keysToRemove :: [String]
> keysToRemove =
>     [ "M-a"
>     , "M1-a"
>     ]
> keysToAdd :: [(String, X ())]
> keysToAdd =
>     [ ("M-a", spawn "xmessage M-a")
>     , ("M1-a", spawn "xmessage M1-a=Alt-a")
>     ]
>
> The `keysToRemove` there is not necessary; `additionalKeysP` will override
any existing bindings for those keys. Additionally, since you are not
including it in the config you pass to `checkKeymap`, it would not know
that you had removed them.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by schoettl** [comment]
Oh ok, that makes sense! Thank you!

**Comment by schoettl** [comment]
It is a bit more tricky to fix than I first thought. My configuration uses a xmobar process handle and when I extract `myConfig` I have to pass this handle along...

I think in this case I just try @byorgey 's second solution and also extract `myModMask`.

**Comment by geekosaur** [comment]
On Fri, Sep 18, 2015 at 1:06 PM, Jakob Schöttl <notifications@github.com>
wrote:

> It is a bit more tricky to fix than I first thought. My configuration uses
> a xmobar process handle and when I extract myConfig I have to pass this
> handle along...
>

checkKeymap does not use that part of the config, so you can just pass
`undefined`.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by schoettl** [comment]
Ok,  I did not know about `undefined`. Thanks!

But I would have to pass the xmobar handle not only to `myConfig` but also to `myLogHook` and `myStartupHook` and later maybe more... it's a chain of parameter passing (`undefined` or a value) and that's why I prefer the second solution.

**Comment by geekosaur** [comment]
On Fri, Sep 18, 2015 at 1:18 PM, Jakob Schöttl <notifications@github.com>
wrote:

> But I would have to pass the xmobar handle not only to myConfig but also
> to myLogHook and myStartupHook and later maybe more... it's a chain of
> parameter passing (undefined or a value) and that's why I prefer the
> second solution.
>
Actually, in that case `undefined` is not the answer.

    myConfig xmproc = {- your config here, using xmproc; pass either xmproc
or undefined in checkKeymap -}
    -- ...
    main = do
      xmproc <- ...
      xmonad $ myConfig xmproc


-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net
