### ISSUE TITLE
ThreeColumns layout hides KDE5 panel

### ISSUE THREAD

**Issue by insysion** [xmonad/xmonad-contrib#306]
### Problem Description

The ThreeColumns layouts is buggy, perhaps only on KDE5. It hides panels. It also does not recover well from changes to the display setup. When switching to an external monitor, I am often faced with a blank screen and have to change the screen layout to get the windows to appear again. After which I can again use the ThreeColumns layouts (hidden panels not withstanding).

I haven't tested against XMonad-testing. Slightly reluctant to try the bleeding edge on a work laptop. But willing to do it if assured it's safe and will help.

### Configuration File

```haskell
module Main (main) where

import XMonad
import XMonad.Config.Kde
import XMonad.Layout.ThreeColumns

main = xmonad kde4Config
    { layoutHook = ThreeColMid 1 (3/100) (1/2)
    }

main :: IO ()
main = xmonad def
```

**Comment by geekosaur** [comment]
When you write `kde4Config { layoutHook = ... }`, you completely replace its `layoutHook` and any other fields of the config record you specify. This will remove `desktopLayoutModifiers` from the `layoutHook`, so docks won't work properly any more.

You might want to read https://wiki.haskell.org/Xmonad/Config_archive/Template_xmonad.hs_(darcs) which talks about how the hooks work, and provides some hints as to how to add to, rather than override, hooks provided by configs.

**Comment by insysion** [comment]
The following works as expected. Thanks @geekosaur :pray:
```
main = xmonad kde4Config
    { layoutHook = desktopLayoutModifiers $ ThreeColMid 1 (3/100) (1/2)
    }
```
