### ISSUE TITLE
BoringWindows lacks boring-aware swapUp/swapDown

### ISSUE THREAD

**Issue by ivanbrennan** [xmonad/xmonad-contrib#374]
### Problem Description

When using Minimize, swapUp and swapDown don't behave correctly if one or more windows on the current workspace are minimized.

For example, on a workspace occupied by three windows _A_, _B_, and _C_, do:
- minimize _B_
- focus _A_
- swapDown

Rather than swapping _A_ and _C_, nothing happens. The same is true if _C_ is focused and you try swapUp.

It seems as if the minimized windows are not totally ignored by the swap behavior, and attempted swaps appear to do nothing until you repeat enough swaps to traverse any minimized windows that were "in the way".

### Configuration File
I put together a demonstration in this [xmonad-testing commit](https://github.com/ivanbrennan/xmonad-testing/commit/cfddc696f1381d64cf59b77bbf4854d50186e7cf), using the following config:
```haskell
import XMonad
import qualified XMonad.StackSet as W
import XMonad.Actions.Minimize
import XMonad.Layout.Minimize
import qualified Data.Map as M

main :: IO ()
main = xmonad def
  { layoutHook = minimize (layoutHook def),
    keys = const . M.fromList $
      [ ((mod4Mask, xK_o), spawn (terminal def)),
        ((mod4Mask, xK_minus), withFocused minimizeWindow),
        ((mod4Mask, xK_equal), withLastMinimized maximizeWindowAndFocus),
        ((mod4Mask .|. shiftMask, xK_Up), windows W.swapUp),
        ((mod4Mask .|. shiftMask, xK_Down), windows W.swapDown)
      ]
  }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by byorgey** [comment]
Hi, thanks for the report!

The fundamental problem is that the xmonad core library has no concept of windows being minimized.  The way`XMonad.Layout.Minimize` works is using `XMonad.Layout.Boring`, which keeps track of a set of windows that should be considered boring.  It also provides its own versions of functions like `focusUp` and `focusDown`, which act just like the versions from the xmonad core except that they take into account skipping boring windows.  To use it, you must import this module and use the versions of `focusUp` and `focusDown` that it provides instead of the ones from the core library.

However, the `swapUp` and `swapDown` functions you are using in the example are from the xmonad core, so they do not know (indeed, they have no way to possibly know) anything about which windows are supposed to be minimized.  They simply do the same thing they would have done with the full set of windows, whether minimized or not; your assessment of what is going on ("It seems as if the minimized windows are not totally ignored...") is exactly right.

So there is actually no way to "fix" `swapUp` and `swapDown` without a major refactoring of the xmonad core. However, what could be done is to add minimization-aware versions of `swapUp` and `swapDown` to `XMonad.Layout.Boring`, just like what is already done with `focusUp` and `focusDown`.  Then you just would have to make sure to import them from that module instead of getting them from the xmonad core.  I think this would make a nice little project for someone wanting to contribute and to learn about how xmonad's `StackSet` works.

**Comment by ivanbrennan** [comment]
@byorgey Thanks for the detailed explanation! That all makes sense. I think I'll try my hand at writing those minimization-aware swap functions.
