### ISSUE TITLE
export addDescrKeys'

### ISSUE THREAD

**Issue by maxigit** [xmonad/xmonad-contrib#47]
At the moment only `addDescrKey` is exported. The problem is it adds defaultKeyBindings.
This is not helpfull if you don't want to keep the original keybindings.

**Comment by geekosaur** [comment]
Looks to me like it already is? What version of xmonad-contrib are you talking about?
(Also it would have helped to mention that you were talking about XMonad.Util.NamedActions.)

https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Util/NamedActions.hs#L27
added by https://github.com/xmonad/xmonad-contrib/commit/10ee484a5948f3e04e94c470f53951d4b1b0b936 from 2013.

**Comment by maxigit** [comment]
It is in the code indeed. However not on my package version. According to `ghc-pkg`, I'm using `xmonad-contrib-0.11.3` which I got by installing ubuntu 15  and the `apt update; apt-get install xmonad`. This package doesn't seem to have `addDescrKeys'` exported, and neither the official (?) documentation found there http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Util-NamedActions.html. Maybe the github code hasn't been push properly ?

**Comment by geekosaur** [comment]
Ubuntu is not rolling release. If you want them to update, you need to talk to the Ubuntu package maintainer, and probably it would not happen anyway without a new full Ubuntu release (they're likely to only do security updates otherwise). Perhaps you would be better off running Arch or Gentoo, or another rolling-release Linux.

**Comment by liskin** [comment]
Not sure if switching distros is a sensible recommendation, to be honest. If one absolutely must use a binary package of xmonad (which makes very little sense), then grabbing a package from Debian and installing it on Ubuntu will most likely work just fine.

**Comment by geekosaur** [comment]
The suggestion to switch distributions was based on the expectation that a new upstream release would automatically lead to a new distribution package; this is quite simply false unless running a rolling release distribution. Ubuntu's not as bad as Debian when it comes to upgrading its packages --- really, did you intend to suggest installing a Debian package? Ubuntu is roughly equivalent to Debian testing, Debian stable packages are usually even older and Debian unstable is not guaranteed to work without many other package upgrades --- but it's still not going to track current versions.

More commonly, many of us run xmonad from git instead of from any OS distribution packages. If you don't want to do this, you could look for someone who provides a PPA.

**Comment by liskin** [comment]
I did really suggest installing a Debian package. Debian testing _is_ rolling release and has had xmonad 0.12 since January. And I did check the likelihood of specifically that package being installable to an older system like Ubuntu, although just by skimming through the deps.

But I can agree that compiling xmonad from git is the best option. Configuring xmonad involves compilation so there's little reason not to compile the whole thing.

**Comment by maxigit** [comment]
That doesn't change the fact that the xmonad website is out of date too.
Also, this commit is nearly 3 year old I'm just surprised is still not in
Ubuntu. I can compile from source (now I know I need too) I'm just
surprised that Ubuntu AND XMonad website are missing such old commits.
Maybe something needs to be updated somewhere or at least checked.

**Comment by geekosaur** [comment]
We don't release very often --- and the problems around the recent 0.12 are an example of why we don't. There's a major bug related to ManageDocks; I've been trying to push for an 0.12.1 but I don't know what all goes into a release currently. And evidently even the people who supposedly do, don't fully, as you noted with the website not being updated. :/

(I'm essentially an X11 subject matter expert, not really the project lead. OTOH nobody else seems to be into being project lead either, which is why I pushed the project onto github with about a day to spare before the old bug tracker shut down and rumors going around about code.haskell.org going away. I'm pretty clueless about the administrative aspects tbh.)

**Comment by maxigit** [comment]
Fair enough, I was just surprised this function wasn't exported (according
to the official doc) but it is. I'll just have to use the git version.
