### ISSUE TITLE
JumpToLayout not working

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#528]
### Problem Description
`JumpToLayout` is used in `XMonad.Prompt.Layout`. Either directly use it or use `layoutPrompt` does not work.

### Steps to Reproduce

Use 
```
layoutPrompt :: XPConfig -> X ()
```
Or
```
sendMessage $ JumpToLayout "tall"
```
I am now testing to see if it works in version 0.16, and if works, I will do git bisect.
UPDATE: 
Not working with
```
xmonad 0.15
xmonad-contrib 0.16
```
### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
On Fri, Apr 23 2021 22:17, oogeek wrote:
> ### Problem Description
> `JumpToLayout` is used in `XMonad.Prompt.Layout`.
> 1. either directly use it or use `layoutPrompt` does not work.

I'm not sure what you're saying here?  The documentation of X.P.Layout
says 

> Also, you can only select layouts if you are using NewSelect, rather
> than the Select defined in xmonad core

It only works when you use X.L.LayoutCombinators.(|||) instead of
X.L.(|||) for your layouts (though hopefully these will be combined soon
when #493 and xmonad/xmonad/281 are merged).

**Comment by oogeek** [comment]
> X.L.LayoutCombinators.(|||)
Oh, let me try it.
