### ISSUE TITLE
Fix `hlint` hints

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#537]
### Problem Description
This is from `XMonad.Doc.Developing`
> Code should be free of any warnings or errors from the Hlint tool; use your best judgment on some warnings like eta-reduction or bracket removal, though.

Currently, there are 1008 hints generated with the default hlint settings. Here's the (HTML) report: https://gist.github.com/TheMC47/ca419fc5c45da224e2ac0a1da2493f1b. I think we should make a list of hints that we want to apply, push the fixes, and make hlint part of the pipeline (maybe have it run on diffs when creating a PR)

@geekosaur @slotThe @liskin  what do you think?

related: #524 

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  ~- [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~

**Comment by liskin** [comment]
I'd start with GHC warnings first. :-)
(I think I mentioned this before.)

**Comment by slotThe** [comment]
> I'd start with GHC warnings first. :-)

[Should](http://ix.io/3ntv) be done

**Comment by liskin** [comment]
> [Should](http://ix.io/3ntv) be done

Awesome!

Thanks for taking the initiative.

**Comment by TheMC47** [comment]
Kudos @slotThe  :tada:

**Comment by slotThe** [comment]
Whoever feels up for applying (some of) the hlint nits, I suggest they use something like [apply-refact](https://hackage.haskell.org/package/apply-refact-0.9.3.0)

**Comment by TheMC47** [comment]
It might be worth it to first discuss what exactly we want to fix

**Comment by liskin** [comment]
> It might be worth it to first discuss what exactly we want to fix

Fair enough. Here's what we can do: Once I port the CI refactors from X11/xmonad to xmonad-contrib, we can try enabling hlint in the haskell-ci workflow and see what comes out of it, and we'll have something tangible to discuss.

**Comment by slotThe** [comment]
According to the overview that @TheMC47 [linked] at the start, this is
the complete list:

<details>
  <summary>The complete list</summary>

  - Warning: Avoid lambda (3)
  - Warning: Avoid reverse (1)
  - Warning: Eta reduce (67)
  - Warning: Evaluate (2)
  - Warning: Fuse mapM_/map (2)
  - Warning: Monad law, left identity (1)
  - Warning: Redundant bracket (97)
  - Warning: Redundant do (5)
  - Warning: Redundant flip (1)
  - Warning: Redundant if (2)
  - Warning: Redundant lambda (4)
  - Warning: Redundant return (1)
  - Warning: Unused LANGUAGE pragma (52)
  - Warning: Use . (1)
  - Warning: Use <$> (1)
  - Warning: Use <|> (1)
  - Warning: Use any (1)
  - Warning: Use asks (1)
  - Warning: Use concat (1)
  - Warning: Use concatMap (14)
  - Warning: Use elemIndex (2)
  - Warning: Use exitSuccess (6)
  - Warning: Use fewer imports (1)
  - Warning: Use find (3)
  - Warning: Use forM_ (3)
  - Warning: Use fromMaybe (46)
  - Warning: Use last (1)
  - Warning: Use map (2)
  - Warning: Use mapM_ (3)
  - Warning: Use mapMaybe (5)
  - Warning: Use maybe (1)
  - Warning: Use notElem (4)
  - Warning: Use replicateM_ (1)
  - Warning: Use snd (2)
  - Warning: Use sortOn (9)
  - Warning: Use takeWhile (1)
  - Warning: Use tuple-section (13)
  - Warning: Use unless (3)
  - Warning: Use unwords (3)
  - Warning: Use when (5)
  - Suggestion: Avoid lambda (17)
  - Suggestion: Avoid lambda using `infix` (2)
  - Suggestion: Fuse foldr/map (3)
  - Suggestion: Move brackets to avoid $ (29)
  - Suggestion: Reduce duplication (8)
  - Suggestion: Redundant $ (67)
  - Suggestion: Redundant bracket (308)
  - Suggestion: Replace case with fromMaybe (1)
  - Suggestion: Replace case with maybe (3)
  - Suggestion: Use ++ (1)
  - Suggestion: Use : (3)
  - Suggestion: Use <$ (1)
  - Suggestion: Use <$> (15)
  - Suggestion: Use =<< (1)
  - Suggestion: Use == (1)
  - Suggestion: Use >=> (1)
  - Suggestion: Use String (10)
  - Suggestion: Use const (5)
  - Suggestion: Use first (4)
  - Suggestion: Use fmap (1)
  - Suggestion: Use guards (13)
  - Suggestion: Use head (1)
  - Suggestion: Use if (5)
  - Suggestion: Use infix (8)
  - Suggestion: Use lambda-case (2)
  - Suggestion: Use let (1)
  - Suggestion: Use list comprehension (8)
  - Suggestion: Use list literal (1)
  - Suggestion: Use map once (1)
  - Suggestion: Use negate (2)
  - Suggestion: Use newtype instead of data (61)
  - Suggestion: Use null (5)
  - Suggestion: Use record patterns (11)
  - Suggestion: Use second (2)
  - Suggestion: Use section (12)
  - Suggestion: Use tuple-section (5)
  - Suggestion: Use uncurry (6)
  - Suggestion: Use void (3)
  - Suggestion: Use withFile (1)
  - Suggestion: Use zipWith (7)

</details>

I think that _a priori_ none of the warnings sounds bad; they should all
be okay.  Contentious ones are perhaps

  - Warning: Eta reduce (67)         (could hamper readability)
  - Warning: Redundant bracket (97)  (could hamper readability)

Most suggestions are also seem very sensible.  However, some may change
strictness behaviour (`Use newtype instead of data`, though a "more
strict" version is usually what one wants) or result in less-readable
code; e.g.:

```
  XMonad/Actions/TagWindows.hs:186:16: Suggestion: Use <$>
  Found

  gets (concat . map (integrate' . stack) . workspaces . windowset)
    >>= mapM getTags
    >>= return . nub . concat

  Perhaps

  (nub . concat)
    <$>
      (gets (concat . map (integrate' . stack) . workspaces . windowset)
         >>= mapM getTags)
```

In my opinion, the current version is much easier to read.  It would
perhaps be better to use

``` haskell
  gets (concat . map (integrate' . stack) . workspaces . windowset)
    >>= mapM getTags
    <&> return . nub . concat
```

but since this can't be automated I wonder if it's worth it.  We should
probably go through the suggestions more carefully and decide which ones
we actually want to enforce.

[linked]: https://gist.github.com/TheMC47/ca419fc5c45da224e2ac0a1da2493f1b

**Comment by TheMC47** [comment]
Thanks for summarizing the report into something more readable. 

Regarding the Eta reductions, I think we should apply this one and locally disable it when we think it's harmful. I also think applying fixes to redundant brackets is also beneficial (not sure if there's an example where brackets are better).

Regarding <$>, I think you make a good point, the second version is worse... There are only 15 of them, so I could probably go through them manually

**Comment by slotThe** [comment]
This should be fixed by a combination of bd5b969d9ba24236c0d5ef521c0397390dbc4b37 and 402d29b306950b9f74664b7652d2b9f3bfa40895 so I'm closing this.

I suppose we can still use this to discuss whether we want to enforce some hints that hlint does not enable by default (can't think of any right now, but this came up in IRC today)

**Comment by eppolito** [comment]
I noticed a GHC warning while building today, and I decided it might be a good idea to also run `hlint`.  I got a bunch of suggestions.  I'm wondering if I should submit a pull request for this?

**Comment by geekosaur** [comment]
The problem with both of those is that we support old ghc versions, and there is no way to silence either of those without breaking compatibility with those old versions.

**Comment by slotThe** [comment]
However, provided that the test run through on older version do feel free to submit a pull request with changes :)

**Comment by liskin** [comment]
Also note that we have hlint in our CI: https://github.com/xmonad/xmonad-contrib/actions/workflows/hlint.yaml and it's green, so if you're getting additional suggestions that's either because it's a different version of hlint (⇒ the PR should bump the version we run in CI) or because we configured those suggestions to be ignored (⇒ the PR should unignore the suggestions that it fixes).
