### ISSUE TITLE
EWMH windows ordering

### ISSUE THREAD

**Issue by kurnevsky** [xmonad/xmonad-contrib#567]
Currently xmonad sets ewmh windows with focused window first, and sometimes it's not very convenient. For instance, it causes taffybar to redraw windows icons in its workspaces widget each time focus is changed, and focused window will be displayed first. It's quite confusing because you can't follow focus visually (taffybar highlights focused window).

What was the reasoning of this behavior? Could it be changed to just use `W.integrate'` [here](https://github.com/xmonad/xmonad-contrib/blob/5fffe03e063aef25881230918cc249f9143f7d80/XMonad/Hooks/EwmhDesktops.hs#L175)?

**Comment by kurnevsky** [comment]
Here what I had to do in my config to avoid this: https://github.com/kurnevsky/dotfiles/commit/59a5d090746bdf1dd180a8c9de416997a4d6161e

**Comment by slotThe** [comment]
Mh, [the spec](https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html#idm45545482105264) says: 

> _NET_CLIENT_LIST has initial mapping order, starting with the oldest window. _NET_CLIENT_LIST_STACKING has bottom-to-top stacking order. These properties SHOULD be set and updated by the Window Manager. 

so it seems like we are indeed violating this currently.  This should definitely be changed, but keeping a list of a) window recency and b) stacking order sounds much more complicated than just using `integrate'` :/

**Comment by kurnevsky** [comment]
> a) window recency

Can't we just assume that windows in `StackSet` are sorted by recency? It'll be true unless user swaps windows itself, and this seems pretty logical that they will be swapped in `_NET_CLIENT_LIST` as well. Otherwise it might be confusing that windows displayed in status bar have different ordering than sidplayed by xmonad. And as for me I'd definitely not like it and would hack this in a similar way :)

> b) stacking order sounds much more complicated than just using integrate' :/

How is it more complicated? Are there multiple good ways we can convert it to a plain list? Wouldn't `integrate'` be good enough?

**Comment by kurnevsky** [comment]
ok, I guess this ordering was done specifically for `_NET_CLIENT_LIST_STACKING` so we can leave it as is and just change `_NET_CLIENT_LIST`.

**Comment by kurnevsky** [comment]
> b) stacking order sounds much more complicated than just using integrate' :/

I think we should do the following (which is a bit different than what have now): `l ++ reverse r ++ [x]`. First from the end should be focused window, then windows that will follow next when we call `focusDown` which means reversed `r` and then windows that will follow next after `focusUp` which is just `l`. Seems like the best possible fit that we can have, since stacking order is not clearly defined.

**Comment by slotThe** [comment]
On Tue, Jun 29 2021 11:12, Evgeny Kurnevsky wrote:
> Can't we just assume that windows in `StackSet` are sorted by recency?

I don't think so, how would that work?  A newly spawned window with
focus is surely the most recently mapped window and should thus be put
last in _NET_CLIENT_LIST (perhaps this is the intention behind the
current implementation?).  Using `integrate` already violates this.
However, just cycling through windows should of course do nothing to the
initial mapping order (or should it?  what if windows get unmapped
because layout say so?  I'm not sure just how initial "initial" means
here).

On top of that, users can of decide (via X.H.InsertPosition or similar
functionality) quite freely where to insert new windows, so even that
"if you are in the master pane everything lines up" assumptions doesn't
really work.

Pragmatically speaking, not many people seem to have noticed this,
meaning we may get away with applying your proposed change.  However,
this doesn't feel quite right to me and I would like some more opinions
from the X11 gurus around here :) @geekosaur @liskin

**Comment by geekosaur** [comment]
Mapping order is kinda not entirely defined for tiling window managers: consider that `Full` unmaps all but the current window, and what window gets mapped next depends on (for example) whether you use `mod`-`k` vs. `mod`-`j` vs. something like `rotOpposite`. (Note also that the module providing `rotOpposite`, `X.A.CycleWindows`, also has its own idea of what constitutes "recent windows".)

**Comment by kurnevsky** [comment]
> A newly spawned window with focus is surely the most recently mapped window and should thus be put last in _NET_CLIENT_LIST

Right, somehow I supposed that newly opened window is always first, which is not true, of course. Then it means that if we fully comply with the spec we won't have good windows ordering in taffybar and probably other status bars that use it...
But if we are not compliant now anyway, probably makes sense to change the ordering to simple `integrate'`? But I'm biased here - it's the behavior I'd like to have myself :)

> consider that Full unmaps all but the current window

But this will affect cycling over layouts too, right? Other layouts will have different windows positions depending on these user actions. So we have to define the ordering somehow anyway. I just suggest to make this ordering consistent with what we set to `_NET_CLIENT_LIST`.

**Comment by kurnevsky** [comment]
Also just realized that if we just open several windows one after another, according to the spec newer windows should appear after older, i.e. they should have ordering `1 2 3`. But in xmonad we will have ordering `3 2 1` :)
We could make it `1 2 3` but then with default windows cycling we will go in the reversed direction...

**Comment by kurnevsky** [comment]
Here found some more info about this ordering which justifies my fix a bit: https://github.com/xiaq/mindock#why-another-dock

**Comment by kurnevsky** [comment]
Checked i3 and they indeed set here initial mapping order: https://github.com/i3/i3/blob/abbf6a85d712ef1790b02122eb432e4bafe20576/src/x.c#L1258

But they didn't have any discussion on this: https://github.com/i3/i3/issues/1099

**Comment by kurnevsky** [comment]
And awesome just sets their stack there which should be similar what I'm doing in my PR: https://github.com/awesomeWM/awesome/blob/d2dc428e567e378a3f534c4d748543413fc30172/ewmh.c#L276

**Comment by kurnevsky** [comment]
So looks like it should be good enough, and anyway better than what we have now.

**Comment by liskin** [comment]
Unfortunately I have absolutely no idea how `_NET_CLIENT_LIST`/`_NET_CLIENT_LIST_STACKING` are used practice. I don't think anything in my setup cares about any particular ordering there, so I'm probably personally fine with changing it to whatever fixes issues for others.

I'll also note that if we wanted to conform to the spec, there probably is a non-intrusive way to do that: introduce an optional LayoutModifier that a) tracks when windows first appear; b) captures the stacking order produced by the underlying layout. EwmhDesktops would then just consult an extensible state variable and use that (with a fallback, as this LayoutModifier would be optional and meant to only be used by people who need that sort of thing).

**Comment by kurnevsky** [comment]
I think (though not completely sure) that `_NET_CLIENT_LIST` was meant to have the same order that we will get switching windows via alt+tab or whatever. It looks like (most?) stacking window managers don't have a way to reorder windows so they will cycle windows in order they were created. So that's why it's described in the specs, but it doesn't fit tiling window managers.

**Comment by granolaonicecream** [comment]
Chiming in half a year later on a closed issue. 
I get that the ideas behind these two atoms are slightly at odds with tiling window managers since the concept of window focus is different, but here's my take:

`_NET_CLIENT_LIST_STACKING` should be analogous to the actual visual stacking (z position) of floating windows, regardless of layout.  I would expect it to match the order of [XQueryTree](https://tronche.com/gui/x/xlib/window-information/XQueryTree.html) on the root window.

I came across the current behavior while trying to write a WM agnostic desktop pager.  It would be nice to be able to process this atom since it could be used to draw without thinking about overlapping windows.  Especially since things like XQueryTree include (tons of) unmapped windows.

>introduce an optional LayoutModifier that a) tracks when windows first appear; b) captures the stacking order produced by the underlying layout.

I might try implementing this eventually.
