### ISSUE TITLE
Throw warning or error when windowPrompt fails due to lack of font

### ISSUE THREAD

**Issue by PapuaHardyNet** [xmonad/xmonad-contrib#723]
### Problem Description

```haskell
import XMonad
import XMonad.Config.Desktop
import XMonad.Prompt
import XMonad.Prompt.Window
import XMonad.Util.EZConfig (additionalKeys)

myMod = mod4Mask

main =
  xmonad $
    desktopConfig
      { terminal = "st",
        modMask = myMod
      }
      `additionalKeys` [ ((myMod, xK_BackSpace), windowPrompt def Goto allWindows)
                       ]
```

Given the above config and the lack of the default ~~prompt~~ font, xmonad should throw an error or a warning either during recompile time or when pressing the keybind using `windowPrompt` to tell the user that the required font is missing. Silent failure should not occur.

A silent failure occurs.

### Steps to Reproduce

Use the above config, but on a machine without bitmap fonts.

### Configuration File

Provided above.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.15-188 (commit XXX if using git)
    - [x] With `xmonad-contrib` version 0.16-170 (commit XXX if using git)

**Comment by TheMC47** [comment]
Probably nothing we can do during compile/recompile. Maybe we'd have a module to show runtime warnings, but there are a couple of questions: should it be configurable? is it "opt-in", or can other modules use it without the user explicitly turning it on?

**Comment by slotThe** [comment]
On Thu, Jun 02 2022 00:10, Yecine Megdiche wrote:
> Probably nothing we can do during compile/recompile.

Yes, I reckon we can only know this once opening the font fails.  

> Maybe we'd have a module to show runtime warnings, but there are a
> couple of questions: should it be configurable? is it "opt-in", or can
> other modules use it without the user explicitly turning it on?

The easiest way would be to just open an xmessage prompt; the
"infrastructure" for this is already there since we use it for
compilation warnings.  I was thinking about whether we should make it
opt-in but for situations like this—things simply not working and
failing silently—I don't think we're missing out much by not doing that.

Having written all of this and seeing the version numbers in the report,
this issue is already fixed isn't it?  We now explicitly set the default
font to xft:monospace if xmonad was compiled with xft support (which is
on by default).  Maybe this issue is not an issue after all :)

**Comment by geekosaur** [comment]
It would probably still be good to catch the error and display a message, because people copy configs around and might not notice that they use e.g. `SauceCodePro Nerd Font Mono` or one of the other fancy fonts.

**Comment by geekosaur** [comment]
(I copied that from an actual config I tested locally, btw)

**Comment by slotThe** [comment]
> It would probably still be good to catch the error and display a message, because people copy configs around and might not notice that they use e.g. `SauceCodePro Nerd Font Mono` or one of the other fancy fonts.

I just saw that `initCoreFont` and `initUtf8Font` do have a fallback in case something goes wrong, just that didn't make its way to `initXMF`...  What would be better in that case?  Fall back to something like `xft:monospace` or really bring up xmessage yelling at the user that the font couldn't be found?  I guess the conventional solution would be the former.

@PapuaHardyNet what would you, as a user, prefer?
